### ISSUE TITLE
bin/mida displays itemscope and page_url info with -v option

### ISSUE THREAD

**Issue by lawrencewoodman** [LawrenceWoodman/mida#1]
`mida -v http://trustafriend.com/reviews/the-rectory-bar-and-restaurant-st-pauls-square-hockley-birmingham/`
The above command gives the following output with itemscope and page_url information that shouldn't be in there:

```
:type: http://schema.org/Organization
:properties: 
  name: 
  - The Rectory Bar and Restaurant
  aggregateRating: 
  - !ruby/object:Mida::Itemscope 
    id: 
    itemscope_node: !ruby/object:Nokogiri::XML::Element {}

    page_url: http://trustafriend.com/reviews/the-rectory-bar-and-restaurant-st-pauls-square-hockley-birmingham/
[SNIP]
```
